backend/models/Statistics.php
<?php

namespace backend\models;

use Yii;
use yii\base\Model;

/**
 * EntitySearch represents the model behind the search form of `common\models\Entity`.
 */
class Statistics extends Model
{

}

backend/controllers/StatisticsController.php
<?php

namespace backend\controllers;

use backend\models\BotUsersSearch;
use backend\models\EntitySearch;
use backend\models\FoodSearch;
use backend\models\UserSearch;
use common\models\BotUsers;
use common\models\Orders;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StatisticsController implements the CRUD actions for Statistics model.
 */
class StatisticsController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $orderPrice = Orders::find()->select('AVG(totalPrice)')->column();
        return $this->render('index', [
            'orderAveragePrice' => isset($orderPrice[0]) ? $orderPrice[0] : 0,
        ]);
    }

    public function actionEntity()
    {
        $searchModel = new EntitySearch();
        $dataProvider = $searchModel->searchTopEntity();

        return $this->render('entity', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTopFood()
    {
        $searchModel = new FoodSearch();
        $dataProvider = $searchModel->searchTopFood();

        return $this->render('food', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTopUsers(){
        $searchModel = new BotUsersSearch();
        $dataProvider = $searchModel->searchTopUsers();

        return $this->render('users', [
            'dataProvider' => $dataProvider,
        ]);
    }
}

backend/views/statistics/entity.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\EntitySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('main', 'Top Entities');
$this->params['breadcrumbs'][] =['label' => 'Statistics', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entity-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'sale'
        ],
    ]); ?>
</div>

backend/views/statistics/food.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\FoodSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('main', 'Top Food');
$this->params['breadcrumbs'][] =['label' => 'Statistics', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="food-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'amount',
        ],
    ]); ?>
</div>

backend/views/statistics/index.php
<?php

/* @var $this yii\web\View */
/* @var int $orderAveragePrice  */

use yii\helpers\Url;

$this->title = 'Statistics';
?>
<style>
    .card-counter {
        height: 60px;
    }

    .card-counter .count-name {
        position: unset !important;
        text-align: center;
        opacity: 1;
    }
</style>
<h4>Average order price: <?= number_format($orderAveragePrice) ?> UZS</h4>
<div class="site-index">

    <div class="row">
        <div class="col-md-3">
            <a href="<?= Url::to(['statistics/entity']) ?>">
                <div class="card-counter primary">
                    <span class="count-name">Top entity</span>
                </div>
            </a>
        </div>

        <div class="col-md-3">
            <a href="<?= Url::to(['statistics/top-food']) ?>">
                <div class="card-counter danger">
                    <span class="count-name">Top food</span>
                </div>
            </a>
        </div>

        <div class="col-md-3">
            <a href="<?= Url::to(['statistics/top-users']) ?>">
                <div class="card-counter success">
                    <span class="count-name">Top users</span>
                </div>
            </a>
        </div>

    </div>

</div>

backend/views/statistics/users.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\BotUsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('main', 'Top Users');
$this->params['breadcrumbs'][] =['label' => 'Statistics', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entity-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'first_name',
            'last_name',
            'phone',
            'amount',
            'price',
        ],
    ]); ?>
</div>