cabinet/controllers/OrdersController.php
<?php

namespace cabinet\controllers;

use api\response\LabeledPrice;
use common\helpers\GeneralHelper;
use common\models\Basket;
use common\models\BotUsers;
use common\models\FoodLink;
use common\models\Invoice;
use common\models\Photos;
use common\models\RejectedFoodLog;
use Faker\Provider\Base;
use Yii;
use common\models\Orders;
use cabinet\models\OrdersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionReject($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate(['removedItems'])) {
            $model->status = $model::STATUS_REJECTED;
            $model->save(false);
            GeneralHelper::rejectOrder($model);
            return $this->redirect(['index']);
        }


        return $this->render('reject', [
            'model' => $model,
        ]);
    }

    public function actionAcceptToProcess($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->validate(['period'])) {
            $model->status = $model::STATUS_IN_PROCESS;
            $model->save(false);
            GeneralHelper::sendOrderTime($model);
//            $basket = Basket::findAll([['order_id' => $model->id]]);
            GeneralHelper::sendPushDriver($model->id, 'paid');
            return $this->redirect(['index']);
        }
        return $this->render('accept', [
            'model' => $model,
        ]);
    }

    public function actionAcceptToApprove($id)
    {
        $model = $this->findModel($id);
        GeneralHelper::sendInvoice($model);
        $model->status = $model::STATUS_APPROVED;
        $model->save(false);
        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrdersSearch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('main', 'The requested page does not exist.'));
    }

    public function actionMyOrders()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->searchMyOrders(Yii::$app->request->queryParams);

        return $this->render('my-orders', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

cabinet/views/orders/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'entity_id')->textInput() ?>

    <?= $form->field($model, 'totalPrice')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'period')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'driver_id')->textInput() ?>

    <?= $form->field($model, 'confirm_code')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'updated_at')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'order_type')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('main', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cabinet/views/orders/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model cabinet\models\OrdersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'entity_id') ?>

    <?= $form->field($model, 'totalPrice') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'period') ?>

    <?php // echo $form->field($model, 'driver_id') ?>

    <?php // echo $form->field($model, 'confirm_code') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'order_type') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('main', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('main', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cabinet/views/orders/accept.php
<?php
/**
 * Created by PhpStorm.
 * User: Shamsidinkhon
 * Date: 12/23/2018
 * Time: 1:31 PM
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Заказы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('main', 'Отказать');


?>
<style>
    input {
        min-width:35px;
        min-height:35px
    }
    </style>
<div class="orders-update">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'period')->radioList($model->getTimes(), [
        'style' => 'display:grid !important; font-size:35px;',
        'required' => true
    ])
        ->label(Yii::t('main', 'Сколько времени требуется для обработки заказа?'), ['style' => 'font-size:35px'])

    ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('main', 'Принять'), ['class' => 'btn btn-success', 'style' => 'font-size:35px']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cabinet/views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = Yii::t('main', 'Create Orders');
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

cabinet/views/orders/index.php
<?php

use common\models\Orders;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel cabinet\models\OrdersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model Orders */

$this->title = Yii::t('main', 'Заказы');
$this->params['breadcrumbs'][] = $this->title;
$this->registerJsFile("/cabinet/web/js/push.js", [View::POS_HEAD]);
$this->registerJs(' 
  Push.Permission.request(onGranted, onDenied);
   function onGranted() {
    }

    function onDenied() {
    }
 ', \yii\web\VIEW::POS_END);
$this->registerJs(' 
    setInterval(function(){  
         $.pjax.reload({container:"#pjaxContainer"});
    }, 10000);', \yii\web\VIEW::POS_HEAD);

$bodyText = Yii::t('main', 'Пожалуйста подтвердите заказ!');
$titleText = Yii::t('main', 'Новый заказ!');
$logo = Yii::getAlias("/cabinet/web/favicon.ico");
$url = Yii::$app->request->absoluteUrl;
$this->registerJs("
$('#pjaxContainer').on('pjax:end', function() {
        if(rowCount > 0){
            Push.create('{$titleText}', {
        body: '{$bodyText}',
        icon: '{$logo}',
        timeout: 5000,
        onClick :function(){
            window.focus();
            this.close();
        },
    });
        }
       });
", $this::POS_READY);
?>

<div class="orders-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php Pjax::begin(['id' => 'pjaxContainer']) ?>
    <?php
    $this->registerJs("
        rowCount  = {$dataProvider->getTotalCount()}
    ;
", $this::POS_READY);
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'rowOptions' => ['style' => 'font-size:20px'],
        'options' => [
            'style'=>'word-wrap: break-word;'
        ],
//        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
//            'totalPrice',
            [
                'label' => Yii::t('main', 'Заказанные Блюда'),
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->getFoods();
                }
            ],
//            [
//                'attribute' => 'order_type',
//                'value' => function ($model) {
//                    return $model->getDeliveryTypes()[$model->order_type];
//                }
//            ],
            [
                'attribute' => 'payment_type',
                'value' => function ($model) {
                    return $model->getPaymentTypes()[$model->payment_type];
                }
            ],
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return $model->getStatuses()[$model->status];
                }
            ],

            [
                'attribute' => 'entity_id',
                'label' => 'Название заведения',
                'value' => function ($model) {
                    return $model->entity->name;
                },
                'visible' => Yii::$app->session->get('current_role_id') == \common\models\UserRoleLink::OPERATOR
            ],

            [
                'label' => Yii::t('main', 'Действия'),
                'format' => 'raw',
                'value' => function ($model) {
                    $btn = '';
                    if ($model->status == Orders::STATUS_NEW && $model->payment_type != Orders::PAY_CASH) {
                        $btn .= Html::a(Yii::t('main', 'Принять'), ['orders/accept-to-approve', 'id' => $model->id], ['class' => 'text-primary', 'style' => 'font-size:20px']);
                        $btn .= Html::a(Yii::t('main', 'Отказать'), ['orders/reject', 'id' => $model->id], [
                            'class' => 'text-danger',
                            'style' => 'font-size:20px;  padding-left:10px;',
//                            'data' => [
//                                'confirm' => Yii::t('main', 'Вы уверены, что хотите отменить заказ?'),
//                                'method' => 'post',
//                            ],
                        ]);
                    }
                    if($model->status == Orders::STATUS_PAID && $model->payment_type != Orders::PAY_CASH){
                        $btn .= Html::a(Yii::t('main', 'Подтвердить'), ['orders/accept-to-process', 'id' => $model->id], ['class' => 'text-success', 'style' => 'font-size:20px;  padding-left:10px']);
                    }

                    if($model->status == Orders::STATUS_NEW && $model->payment_type == Orders::PAY_CASH){
                        $btn .= Html::a(Yii::t('main', 'Принять'), ['orders/accept-to-process', 'id' => $model->id], ['class' => 'text-success', 'style' => 'font-size:20px;  padding-left:10px']);
                        $btn .= Html::a(Yii::t('main', 'Отказать'), ['orders/reject', 'id' => $model->id], [
                            'class' => 'text-danger',
//                            'style' => 'font-size:30px; margin-left:5px;',
                            'style' => 'font-size:20px; padding-left:10px',
//                            'data' => [
//                                'confirm' => Yii::t('main', 'Вы уверены, что хотите отменить заказ?'),
//                                'method' => 'post',
//                            ],
                        ]);
                    }
                    $btn .= Html::a(Yii::t('main', 'Посмотреть'), ['orders/view', 'id' => $model->id], ['class' => 'text-info', 'style' => 'font-size:20px;  padding-left:10px']);
                    return $btn;
                }
            ]
            //'order_type',

//            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end() ?>
</div>

cabinet/views/orders/my-orders.php
<?php

use common\models\Orders;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel cabinet\models\OrdersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model Orders */

$this->title = Yii::t('main', 'Заказы');
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="orders-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php Pjax::begin(['id' => 'pjaxContainer']) ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
//        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'totalPrice',
            [
                'label' => Yii::t('main', 'Заказанные Блюда'),
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->getFoods();
                }
            ],
//            [
//                'attribute' => 'order_type',
//                'value' => function ($model) {
//                    return $model->getDeliveryTypes()[$model->order_type];
//                }
//            ],
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return $model->getStatuses()[$model->status];
                }
            ],
            [
                'attribute' => 'entity_id',
                'label' => 'Название заведения',
                'value' => function ($model) {
                    return $model->entity->name;
                },
                'visible' => Yii::$app->session->get('current_role_id') == \common\models\UserRoleLink::OPERATOR
            ],
//            [
//                'label' => Yii::t('main', 'Действия'),
//                'format' => 'raw',
//                'value' => function ($model) {
//                    $btn = '';
//                    if ($model->status == Orders::STATUS_NEW) {
//                        $btn .= Html::a(Yii::t('main', 'Принять'), ['orders/accept', 'id' => $model->id], ['class' => 'btn btn-primary', 'style' => 'font-size:30px']);
//                        $btn .= Html::a(Yii::t('main', 'Отказать'), ['orders/reject', 'id' => $model->id], [
//                            'class' => 'btn btn-danger',
//                            'style' => 'font-size:30px; margin-left:5px;',
////                            'data' => [
////                                'confirm' => Yii::t('main', 'Вы уверены, что хотите отменить заказ?'),
////                                'method' => 'post',
////                            ],
//                        ]);
//                    }
//                    if($model->status == Orders::STATUS_PAID){
//                        $btn .= Html::a(Yii::t('main', 'Подтвердить'), ['orders/accept-to-process', 'id' => $model->id], ['class' => 'btn btn-success', 'style' => 'font-size:30px']);
//                    }
//                    return $btn;
//                }
//            ]
            //'order_type',

//            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end() ?>
</div>

cabinet/views/orders/reject.php
<?php
/**
 * Created by PhpStorm.
 * User: Shamsidinkhon
 * Date: 12/23/2018
 * Time: 1:31 PM
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Заказы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('main', 'Отказать');


?>
<style>
    input {
        min-width:35px;
        min-height:35px
    }
    </style>
<div class="orders-update">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'removedItems')->checkboxList($model->getBasket(), [
        'style' => 'display:grid !important; font-size:35px;',
    ])
        ->label(Yii::t('main', 'Выберите еду, которой сейчас нет'), ['style' => 'font-size:35px']) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('main', 'Отказать'), ['class' => 'btn btn-success', 'style' => 'font-size:35px']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cabinet/views/orders/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = Yii::t('main', 'Update Orders: ' . $model->id, [
    'nameAttribute' => '' . $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('main', 'Update');
?>
<div class="orders-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

cabinet/views/orders/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-view">

    <h1>Номер заказа:  <?= Html::encode($this->title) ?></h1>

    <h3>Данные пользователя:</h3>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'user_id',
                'value' => function ($model) {
                    return $model->user->last_name . ' ' . $model->user->first_name;
                },
                'label' => 'Ф.И.О пользователя'
            ],
            [
                'attribute' => 'user_id',
                'value' => function ($model) {
                    return $model->user->phone;
                },
                'label' => 'Телефон номер пользователя'
            ]
        ],
    ]) ?>
    <p></p>
    <h3>Данные заказа:</h3>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'created_at',
                'label' => 'Дата заказа'
            ],
            [
                'value' => function ($model) {
                    return $model->getFoods();
                },
                'label' => 'Список еды',
                'format' => 'raw'
            ],
            [
                'attribute' => 'totalPrice',
                'value' => function ($model) {
                    return $model->totalPrice . ' UZS';
                }
            ],
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return $model->getStatuses()[$model->status];
                }
            ],
            [
                'attribute' => 'payment_type',
                'value' => function ($model) {
                    return $model->getPaymentTypes()[$model->payment_type];
                },
                'label' => 'Тип оплаты',
            ],
//            'period',
        ],
    ]) ?>
</div>